version: '3'
services:
  api:
    build: ./backend
    command: node index.js
    restart: unless-stopped
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
  chat:
    build: ./chat-service
    command: node index.js
    restart: unless-stopped
    volumes:
      - ./chat-service:/app
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
